easy_admin:
    site_name: '%env(SITE_NAME)%'

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { route: 'security_logout', label: 'Log out', icon: 'sign-out' }

            - { label: 'Matchings' }
            # - { route: 'admin_matches', label: 'Matches', icon: 'check' }
            # - { route: 'admin_match_history', label: 'History', icon: 'history' }
            - { entity: 'Helper', label: 'Helpers', icon: 'users' }
            - { entity: 'HelpRequest', label: 'Help requests', icon: 'handshake-o' }

            # - { label: 'Monitoring' }
            # - { route: 'admin_statistics', label: 'Statistics', icon: 'chart-bar' }
            # - { route: 'admin_unmatched_list', label: 'Unmatched needs', icon: 'search' }

            # - { label: 'Maps' }
            # - { route: 'admin_map_requests', label: 'All requests', icon: 'map-o', target: '_blank' }
            # - { route: 'admin_map_helpers', label: 'Helpers by department', icon: 'map-o' }

            # - { label: 'Export' }
            # - { route: 'admin_export_helpers', label: 'Export helpers', icon: 'cloud-download', target: '_blank' }
            # - { route: 'admin_export_helpers_by_zip_code', label: 'Export zip codes', icon: 'cloud-download', target: '_blank' }
            # - { route: 'admin_export_unmatched', label: 'Export unmatched', icon: 'cloud-download', target: '_blank' }

    entities:
        Helper:
            class: App\Entity\Helper
            disabled_actions: ['show', 'new']
            list:
                title: Helpers
                max_results: 100
                sort: ['createdAt', 'DESC']
                actions:
                    - { name: 'edit', template: 'admin/actions/edit_helper.html.twig' }
                    - { name: 'delete', template: 'admin/actions/delete_helper.html.twig' }
                fields:
                    - id
                    - { property: 'locality', label: 'Commune' }
                    - { property: 'firstName', label: 'First name' }
                    - { property: 'lastName', label: 'Last name' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'phone', label: 'Phone' }
                    - { property: 'createdAt', label: 'Date' }

        HelpRequest:
            class: App\Entity\HelpRequest
            disabled_actions: ['show', 'new', 'edit']
            list:
                title: Help requests
                max_results: 100
                sort: ['createdAt', 'DESC']
                fields:
                    - id
                    - { property: 'locality', label: 'Commune' }
                    - { property: 'type', label: 'Type' }
                    - { property: 'firstName', label: 'First name' }
                    - { property: 'lastName', label: 'Last name' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'phone', label: 'Phone' }
                    - { property: 'createdAt', label: 'Date' }
