easy_admin:
    site_name: '%env(SITE_NAME)%'

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { route: 'security_logout', label: 'Log out', icon: 'sign-out' }

            - { label: 'Users' }
            - { entity: 'Helper', label: 'Helpers', icon: 'users' }
            - { entity: 'HelpRequest', label: 'Help requests', icon: 'medkit' }
            - { entity: 'Volunteer', label: 'Volunteers', icon: 'handshake-o' }

            - { label: 'Monitoring' }
            - { route: 'admin_statistics', label: 'Statistics', icon: 'chart-bar' }
            # - { route: 'admin_unmatched_list', label: 'Unmatched needs', icon: 'search' }

            # - { label: 'Maps' }
            # - { route: 'admin_map_requests', label: 'All requests', icon: 'map-o', target: '_blank' }
            # - { route: 'admin_map_helpers', label: 'Helpers by department', icon: 'map-o' }

            # - { label: 'Export' }
            # - { route: 'admin_export_helpers', label: 'Export helpers', icon: 'cloud-download', target: '_blank' }
            # - { route: 'admin_export_helpers_by_zip_code', label: 'Export zip codes', icon: 'cloud-download', target: '_blank' }
            # - { route: 'admin_export_unmatched', label: 'Export unmatched', icon: 'cloud-download', target: '_blank' }

    entities:
        Helper:
            class: App\Entity\Helper
            disabled_actions: ['show', 'new', 'edit', 'delete']
            list:
                title: Helpers
                max_results: 100
                sort: ['createdAt', 'DESC']
                actions:
                fields:
                    - id
                    - { property: 'firstName', label: 'Profile', template: 'admin/field/profile.html.twig' }
                    - { property: 'email', label: 'Contact details', template: 'admin/field/contact.html.twig' }
                    - { property: 'masks', label: 'Capabilities', template: 'admin/field/capabilities.html.twig', sortable: false }
                    - { property: 'createdAt', label: 'Date' }

        Volunteer:
            class: App\Entity\Volunteer
            disabled_actions: ['show', 'new', 'edit', 'delete']
            list:
                title: Volunteers
                max_results: 100
                sort: ['createdAt', 'DESC']
                fields:
                    - id
                    - { property: 'firstName', label: 'Profile', template: 'admin/field/profile.html.twig' }
                    - { property: 'email', label: 'Contact details', template: 'admin/field/contact.html.twig' }
                    - { property: 'createdAt', label: 'Date' }

        HelpRequest:
            class: App\Entity\HelpRequest
            disabled_actions: ['show', 'new', 'edit', 'delete']
            list:
                title: Help requests
                max_results: 100
                sort: ['createdAt', 'DESC']
                fields:
                    - id
                    - { property: 'type', label: 'Type' }
                    - { property: 'firstName', label: 'Profile', template: 'admin/field/profile.html.twig' }
                    - { property: 'email', label: 'Contact details', template: 'admin/field/contact.html.twig' }
                    - { property: 'createdAt', label: 'Date' }
