framework:
    messenger:
        failure_transport: failed

        transports:
            amqp: '%env(RABBITMQ_URL)%/%2f/messages'
            failed: 'doctrine://default?queue_name=failed'

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': amqp
