twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        analytics_server: '%env(ANALYTICS_SERVER)%'
        team_email: '%env(SENDER_ADDRESS)%'
