parameters: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $locale: '%env(LOCALE)%'
            $sender: '%env(SENDER_ADDRESS)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Model,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
